export const CREATE_SECTION = 'CREATE_SECTION';
export const UPDATE_SECTION = 'UPDATE_SECTION';
export const DELETE_SECTION = 'DELETE_SECTION';
export const MOVE_SECTION = 'MOVE_SECTION';

export const CREATE_INPUT = 'CREATE_INPUT';
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const DELETE_INPUT = 'DELETE_INPUT';
export const MOVE_INPUT = 'MOVE_INPUT';

export const UPDATE_OPTIONS = 'UPDATE_OPTIONS';